## Fichier : docker-compose.yml
version: '3'
services:
  progress:
    container_name: airbnb
    build: .
    ports:
      - "3000:3000"
    # stdin_open: true
    volumes:
       - .:/usr/src/app/airbnb-mui-app
       - /usr/src/app/airbnb-mui-app/node_modules